"""Proactive nudges: morning briefing, overdue accountability, due-today,
evening review, follow-ups. Generated by the nudge engine, surfaced to the
client, and answered (e.g. an overdue reason) by the user.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base_mixin import TimestampMixin, UUIDMixin


class Notification(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "notifications"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    # morning_brief | evening_review | overdue | due_today | followup
    kind: Mapped[str] = mapped_column(String(24), index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    task_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        index=True,
        nullable=True,
    )
    meeting_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("meetings.id", ondelete="CASCADE"),
        index=True,
        nullable=True,
    )
    # pending | answered | dismissed
    status: Mapped[str] = mapped_column(String(16), default="pending", nullable=False)
    # normal (silent badge) | call (ring + vibrate + incoming-call UI)
    alert_level: Mapped[str] = mapped_column(String(8), default="normal", nullable=False)
    # If set and in the future, the nudge is hidden until then (snooze).
    snoozed_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
